/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Cat API
 * ![image](https://s3-us-west-2.amazonaws.com/tdapi-live/static/tie-square-135.png)

## An open, free, read & write API all about Dogs
The Cat API gives you access to 1000's of dog images, and breeds.
- Upload your own images
- Detailed info on all the Breeds
- Favourite or Vote on images
- Get stats on your requests
- Save a custom value with each request

## How is this free?
Our goal is to create free, fun & useful public service API's, helping people learn to code, create awesome projects, and be a stable fixture in a turbulent world.

## How do i get access?
Just signup for an API Key from https://thecatapi.com for free. We're looking forward to seeing what you build!
 * OpenAPI spec version: 1.6.1
 */

export type GetImagesSearchParams = {
  /**
   * [optional] thumb , small, med or full - small is perfect for Discord
   */
  size?: string;
  /**
   * [optional] a comma separated strig of types to return e.g. jpg,png for static, or gif for gifs
   */
  mime_types?: string;
  /**
   * [optional] json | src
   */
  format?: string;
  /**
   * [optional] - only return images with breed data
   */
  has_breeds?: boolean;
  /**
   * [optional] default:RANDOM - RANDOM | ASC | DESC
   */
  order?: string;
  /**
   * [optional] paginate through results
   */
  page?: number;
  /**
   * [optional] number of results to return, up to 25 with a valid API-Key
   */
  limit?: number;

  breed_ids?: string;
};
