/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Cat API
 * ![image](https://s3-us-west-2.amazonaws.com/tdapi-live/static/tie-square-135.png)

## An open, free, read & write API all about Dogs
The Cat API gives you access to 1000's of dog images, and breeds.
- Upload your own images
- Detailed info on all the Breeds
- Favourite or Vote on images
- Get stats on your requests
- Save a custom value with each request

## How is this free?
Our goal is to create free, fun & useful public service API's, helping people learn to code, create awesome projects, and be a stable fixture in a turbulent world.

## How do i get access?
Just signup for an API Key from https://thecatapi.com for free. We're looking forward to seeing what you build!
 * OpenAPI spec version: 1.6.1
 */

export * from "./getBreeds200";
export * from "./getBreedsBreedId200";
export * from "./getBreedsBreedIdFacts200";
export * from "./getBreedsBreedIdFactsParams";
export * from "./getBreedsParams";
export * from "./getBreedsSearch200";
export * from "./getBreedsSearchParams";
export * from "./getFacts200";
export * from "./getFavourites200";
export * from "./getImages200";
export * from "./getImagesBkIEhN3pG200";
export * from "./getImagesParams";
export * from "./getImagesSearch200";
export * from "./getImagesSearch401";
export * from "./getImagesSearchParams";
export * from "./getVotes200";
export * from "./postFavourites200";
export * from "./postFavouritesBody";
export * from "./postImagesImageIdBreedsBody";
export * from "./postImagesUpload201";
export * from "./postImagesUploadBody";
export * from "./postVotes201";
export * from "./postVotesBody";
export * from "./postWebhooks200";
export * from "./postWebhooksBody";
