import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import QueryProvider from "@/contexts/QueryProvider";
import clsx from "clsx";
import NavBar from "@/components/NavBar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "mx-auto max-w-screen-xl px-4 py-8 lg:px-4")}>
        <NavBar />
        <QueryProvider>
          {children}
          <div id="modal-root" />
        </QueryProvider>
      </body>
    </html>
  );
}
